#!/usr/bin/env bash
# This script displays information about subdomains

# Function to display subdomain information
display_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
    local destination=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main function
main() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            display_info "$domain" "$sub"
        done
    else
        display_info "$domain" "$subdomain"
    fi
}

# Execute main function with provided arguments
main "$@"
