#!/usr/bin/env bash

# Function to display usage
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    usage
    exit 1
fi

# Assigning parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file using scp
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username"@"$server_ip":~

echo "File transferred successfully."
