#!/bin/bash

# Update package lists
apt-get update

# Install nginx
apt-get install -y nginx

# Define the hostname
hostname=$(hostname)

# Configure nginx to include custom HTTP response header
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_widad _;

    location / {
        proxy_pass http://localhost:5000;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Served-By $hostname; # Set custom HTTP header
    }
}
EOF

# Reload nginx to apply changes
systemctl reload nginx

echo "Nginx configured with custom HTTP response header. X-Served-By: $widad"

