#!/bin/bash

# Define the name of the private key
private_key="school"

# Define the number of bits
bits=4096

# Define the passphrase
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $bits -f $private_key -N $passphrase
